/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminRefreshRouteImport } from './routes/admin.refresh'
import { Route as AppSpotIdRouteImport } from './routes/_app.spot.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminRefreshRoute = AdminRefreshRouteImport.update({
  id: '/admin/refresh',
  path: '/admin/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSpotIdRoute = AppSpotIdRouteImport.update({
  id: '/spot/$id',
  path: '/spot/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin/refresh': typeof AdminRefreshRoute
  '/spot/$id': typeof AppSpotIdRoute
}
export interface FileRoutesByTo {
  '/admin/refresh': typeof AdminRefreshRoute
  '/': typeof AppIndexRoute
  '/spot/$id': typeof AppSpotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin/refresh': typeof AdminRefreshRoute
  '/_app/': typeof AppIndexRoute
  '/_app/spot/$id': typeof AppSpotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/refresh' | '/spot/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin/refresh' | '/' | '/spot/$id'
  id: '__root__' | '/_app' | '/admin/refresh' | '/_app/' | '/_app/spot/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRefreshRoute: typeof AdminRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/refresh': {
      id: '/admin/refresh'
      path: '/admin/refresh'
      fullPath: '/admin/refresh'
      preLoaderRoute: typeof AdminRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/spot/$id': {
      id: '/_app/spot/$id'
      path: '/spot/$id'
      fullPath: '/spot/$id'
      preLoaderRoute: typeof AppSpotIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSpotIdRoute: typeof AppSpotIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSpotIdRoute: AppSpotIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRefreshRoute: AdminRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
